### ISSUE TITLE
Package Control Integration

### ISSUE THREAD

**Issue by leoheck** [noisyass2/SublimeCadenceSkill#1]
Hi, I added your repo to the sublime [package control](https://github.com/wbond/package_control_channel/pull/5450). What do you think?

**Comment by bernard-m-rivera** [comment]
Oh cool. Sorry if this reply is so late. Haven't worked on this for years. Switching jobs and all that. Does anyone actually use this besides me?

**Comment by leoheck** [comment]
Me! Actually, I use it and many others can find and use it if it is easy to install :) 

Once you didn't answer this before, I added my fork of this repo in the Package Control because they require extra config files. I could make a pull request here to add the new stuff here in order to keep your repository linked to the Package Control instead of my fork. What do you think, can we do that?

**Comment by bernard-m-rivera** [comment]
Nah, lets stick with your fork :) No problems here.

**Comment by leoheck** [comment]
Done!

**Comment by leoheck** [comment]
Done.
